// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include "../state.hpp"

namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    virtual ~Action ();
    void apply (state::State& s, bool notify);
  };

};

#endif
