// Generated by dia2code
#ifndef ENGINE__CHOOSEWEAPON__H
#define ENGINE__CHOOSEWEAPON__H

#include "../state.hpp"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ChooseWeapon - 
  class ChooseWeapon : public engine::Action {
    // Attributes
  protected:
    int idx;
    // Operations
  public:
    ChooseWeapon (int idx);
    ~ChooseWeapon ();
    void apply (state::State* s, bool notify);
  };

};

#endif
