// Generated by dia2code
#ifndef ENGINE__CMDTYPEID__H
#define ENGINE__CMDTYPEID__H


namespace engine {

  enum CmdTypeID {
    MOVE_CMD     = 0,
    KILL_CMD     = 1,
    FIRE_CMD     = 2,
    LOAD_CMD     = 3,
    NEXT_CMD     = 4
  };

};

#endif
