// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


#include "CommandTypeID.h"
#include "CommandCategory.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Operations
  public:
    virtual ~Command ();
    virtual int  getCategory () const = 0;
    virtual CommandTypeID getTypeID () const = 0;
  };

};

#endif
