// Generated by dia2code
#ifndef ENGINE__COMMANDCATEGORY__H
#define ENGINE__COMMANDCATEGORY__H


namespace engine {

  enum CommandCategory {
    MAIN_CATEGORY     = 0x100,
    MOVE_CATEGORY     = 0x200,
    MODE_CATEGORY     = 0x300
  };

};

#endif
