// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


#include "CmdTypeID.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    engine::CmdTypeID cmdType;
    // Operations
  public:
    virtual ~Command ();
    virtual CmdTypeID getCmdTypeID () = 0;
  };

};

#endif
