// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeID {
    LOAD     = 1,
    MODE     = 2,
    DIRECTION     = 3
  };

};

#endif
