// Generated by dia2code
#ifndef ENGINE__COMMANDSET__H
#define ENGINE__COMMANDSET__H

#include <vector>

namespace engine {
  class Command;
  class CommandSet;
}

#include "Command.h"

namespace engine {

  /// class CommandSet - 
  class CommandSet {
    // Associations
    // Attributes
  public:
    std::vector<Command*> commands;
    // Operations
  public:
    CommandSet ();
    ~CommandSet ();
    Command* get (int idx);
    void set (Command* cmd);
    void take (CommandSet& commands, bool replace);
  };

};

#endif
