// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMAND__H
#define ENGINE__DIRECTIONCOMMAND__H

#include "../state.hpp"

namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class DirectionCommand - 
  class DirectionCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    state::Direction direction;
    // Operations
  public:
    DirectionCommand (int c, state::Direction d);
    int getCategory () const;
    CommandTypeID getTypeID () const;
    int getCharacter () const;
    state::Direction getDirection ();
  };

};

#endif
