// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include "../state.hpp"
#include <stdint.h>

namespace engine {
  class CommandSet;
  class Ruler;
  class Command;
}

#include "Ruler.h"
#include "CommandSet.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  protected:
    state::ElementFactory factory;
    state::State* currentState;
    CommandSet* currentCommands;
    int64_t lastUpdateTime;
    Ruler* rules;
    // Operations
  public:
    void loadlevel ();
    Engine ();
    ~Engine ();
    state::State* getState ();
    void setState (state::State* s);
    void addCommand (Command* cmd);
    void takeCommands (CommandSet* commands);
    bool update (int64_t time, int64_t* next_time = NULL);
    void setRuler (Ruler* r);
  };

};

#endif
