// Generated by dia2code
#ifndef ENGINE__FIRE__H
#define ENGINE__FIRE__H

#include "../state.hpp"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Fire - 
  class Fire : public engine::Action {
    // Attributes
  protected:
    state::Orientation orientation;
    int puissance;
    // Operations
  public:
    Fire (state::Orientation orientation, int puissance);
    ~Fire ();
    void apply (state::State* s, bool notify);
  };

};

#endif
