// Generated by dia2code
#ifndef ENGINE__FIRECOMMAND__H
#define ENGINE__FIRECOMMAND__H


namespace engine {
  class Command;
}

#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class FireCommand - 
  class FireCommand : public engine::Command {
    // Attributes
  protected:
    int power;
    int x;
    int y;
    int dx;
    int dy;
    bool charging;
    // Operations
  public:
    FireCommand (int power, int x, int y, bool charging);
    CmdTypeID getCmdTypeID ();
    bool isCharging ();
    void setFire (int power, int x, int y, bool charging);
  };

};

#endif
