// Generated by dia2code
#ifndef ENGINE__FIRECOMMAND__H
#define ENGINE__FIRECOMMAND__H

#include "../state.hpp"

namespace engine {
  class Command;
}

#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class FireCommand - 
  class FireCommand : public engine::Command {
    // Attributes
  protected:
    int idx;
    state::Direction direction;
    // Operations
  public:
    FireCommand (int idx, state::Direction d);
    CmdTypeID getCmdTypeID ();
    void setFire (int idx, state::Direction d);
    state::Direction getDirection ();
    int getIDX ();
  };

};

#endif
