// Generated by dia2code
#ifndef ENGINE__KILLFOWL__H
#define ENGINE__KILLFOWL__H

#include "../state.hpp"

namespace engine {
  class FireCommand;
  class Action;
}

#include "Action.h"

namespace engine {

  /// class KillFowl - 
  class KillFowl : public engine::Action {
    // Attributes
  protected:
    int idx;
    FireCommand* fire;
    // Operations
  public:
    KillFowl (int idx, FireCommand* fire);
    KillFowl (int idx);
    ~KillFowl ();
    void apply (state::State* s, bool notify);
    void setIDX (int idx);
  };

};

#endif
