// Generated by dia2code
#ifndef ENGINE__KILLFOWL__H
#define ENGINE__KILLFOWL__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class KillFowl - 
  class KillFowl : public engine::Action {
    // Attributes
  protected:
    int idx;
    // Operations
  public:
    KillFowl ();
    ~KillFowl ();
  };

};

#endif
