// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H


namespace engine {
  class Command;
}

#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  public:
    bool load;
    // Operations
  public:
    LoadCommand (bool load);
    void setLoad (bool load);
    CmdTypeID getCmdTypeID ();
  };

};

#endif
