// Generated by dia2code
#ifndef ENGINE__MOVEFOWL__H
#define ENGINE__MOVEFOWL__H

#include "../state.hpp"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveFowl - 
  class MoveFowl : public engine::Action {
    // Attributes
  protected:
    int idx;
    int dx;
    int dy;
    int dpos;
    state::Direction Orientation;
    state::Direction Direction;
    // Operations
  public:
    MoveFowl (int idx);
    ~MoveFowl ();
    void setCoords (int dx, int dy, int dpos);
    void setOrientation (state::Direction orientation);
    void setDirection (state::Direction direction);
    void Jump (int dx, int dy, int dpos);
  };

};

#endif
