// Generated by dia2code
#ifndef ENGINE__MOVEFOWL__H
#define ENGINE__MOVEFOWL__H

#include "../state.hpp"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveFowl - 
  class MoveFowl : public engine::Action {
    // Attributes
  protected:
    int idx;
    int dx;
    int dy;
    int dpos;
    state::Direction Direction;
    state::Fowl* poule;
    // Operations
  public:
    MoveFowl (int idx);
    ~MoveFowl ();
    void setCoords (int dx, int dy, int dpos);
    void setDir (state::Direction direction);
    void Jump (state::State& s, bool notify);
    void setIDX (int idx);
    int getIDX ();
    state::Fowl* getFowl ();
    void setFowl (state::Fowl* f);
    void isFlying (state::State& s, bool notify);
    void apply (state::State& s, bool notify);
  };

};

#endif
