// Generated by dia2code
#ifndef ENGINE__MOVEID__H
#define ENGINE__MOVEID__H


namespace engine {

  enum MoveID {
    CAMERA     = 1,
    WEAPON     = 2,
    CHICKEN_WALK     = 3,
    CHICKEN_JUMP     = 4
  };

};

#endif
