// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H

#include "../state.hpp"

namespace engine {
  class Command;
}

#include "MoveID.h"
#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Associations
    engine::MoveID moveID;
    // Attributes
  protected:
    int DX;
    int DY;
    int idx;
    state::Direction d;
    // Operations
  public:
    MoveCommand (int dx, int dy, MoveID id, int idx, state::Direction d);
    MoveID getMoveID ();
    CmdTypeID getCmdTypeID ();
    void setMove (int DX, int DY, int idx, state::Direction d);
    void setMoveID (MoveID id);
    void setIDX (int idx);
    int getIDX ();
    state::Direction getDir ();
  };

};

#endif
