// Generated by dia2code
#ifndef ENGINE__MOVEWEAPON__H
#define ENGINE__MOVEWEAPON__H

#include "../state.hpp"

namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveWeapon - 
  class MoveWeapon : public engine::Action {
    // Attributes
  protected:
    int idx;
    int dx;
    int dy;
    int dpos;
    state::Orientation Orientation;
    // Operations
  public:
    MoveWeapon (int idx);
    ~MoveWeapon ();
    void setCoords (int dx, int dy, int dpos);
    void setOrientation (state::Orientation orientation);
    void apply (state::State* s, bool notify);
  };

};

#endif
