// Generated by dia2code
#ifndef ENGINE__MOVEID__H
#define ENGINE__MOVEID__H


namespace engine {

  enum MoveID {
    NONE     = 0,
    WEAPON     = 1,
    CHICKEN_WALK     = 2,
    CHICKEN_JUMP     = 3
  };

};

#endif
