// Generated by dia2code
#ifndef ENGINE__NEXTCOMMAND__H
#define ENGINE__NEXTCOMMAND__H


namespace engine {
  class Command;
}

#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class NextCommand - 
  class NextCommand : public engine::Command {
    // Attributes
  protected:
    int idx;
    bool TeamChange;
    bool FowlHasMoved;
    // Operations
  public:
    NextCommand (int idx, bool TeamChange, bool FowlHasMoved);
    CmdTypeID getCmdTypeID ();
    void setNextCommand (int idx, bool TeamChange, bool FowlHasMoved);
    int getIDX ();
    bool getTeamChange ();
    void setIDX (int idx);
    bool getFowlHasMoved ();
    void setFowlHasMoved (bool FowlHasMoved);
    void setTeamChange (bool TeamChange);
  };

};

#endif
