// Generated by dia2code
#ifndef ENGINE__NEXTCOMMAND__H
#define ENGINE__NEXTCOMMAND__H


namespace engine {
  class MoveFowl;
  class KillCommand;
  class Command;
}

#include "CmdTypeID.h"
#include "Command.h"

namespace engine {

  /// class NextCommand - 
  class NextCommand : public engine::Command {
    // Attributes
  protected:
    int idx;
    MoveFowl* mv;
    KillCommand* KC;
    bool TeamChange;
    bool FowlHasMoved;
    // Operations
  public:
    NextCommand (int idx, MoveFowl* mv, KillCommand* KC, bool TeamChange, bool FowlHasMoved);
    CmdTypeID getCmdTypeID ();
    void setNextCommand (int idx, MoveFowl* mv, KillCommand* KC, bool TeamChange, bool FowlHasMoved);
    int getIDX ();
    MoveFowl* getMoveFowl ();
    KillCommand* getKillCommand ();
    bool getTeamChange ();
    void setIDX (int idx);
    bool getFowlHasMoved ();
    void setFowlHasMoved (bool FowlHasMoved);
    void setTeamChange (bool TeamChange);
  };

};

#endif
