// Generated by dia2code
#ifndef ENGINE__ZOOMOUT__H
#define ENGINE__ZOOMOUT__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ZoomOut - 
  class ZoomOut : public engine::Action {
    // Operations
  public:
    ZoomOut ();
    ~ZoomOut ();
  };

};

#endif
