// Generated by dia2code
#ifndef ENGINE__ZOOMIN__H
#define ENGINE__ZOOMIN__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ZoomIn - 
  class ZoomIn : public engine::Action {
    // Operations
  public:
    ZoomIn ();
    ~ZoomIn ();
  };

};

#endif
