// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class Animation - 
  class Animation {
    // Associations
    // Attributes
  public:
    int i;
  protected:
    int x;
    int y;
    const Tile* tile;
    state::direction direction;
    float speed;
    // Operations
  public:
    Animation (int i, int x, int y, const Tile* a);
    void setDirection (state::Direction d);
    void setSpeed (float speed);
  };

};

#endif
