// Generated by dia2code
#ifndef RENDER__ANIMATEDTILE__H
#define RENDER__ANIMATEDTILE__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class AnimatedTile - 
  class AnimatedTile : public Render::Tile {
    // Attributes
  public:
    int x;
    int y;
    int width;
    int height;
    // Operations
  public:
    AnimatedTile (int x, int y, int w, int h);
    ~AnimatedTile ();
    bool isAnimated () const;
    int getX ();
    int getY ();
    int getWidth ();
    int getHeight ();
    void setX (int x);
    void setY (int y);
    void setWidth (int w);
    void setHeight (int h);
  };

};

#endif
