// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H

#include "../state.hpp"
#include <stdint.h>

namespace Render {
  class Tile;
}

#include "state/Direction.h"
#include "Tile.h"

namespace Render {

  /// class Animation - 
  class Animation {
    // Associations
    // Attributes
  protected:
    int i;
    int x;
    int y;
    const Tile* tile;
    state::Direction direction;
    float speed;
    // Operations
  public:
    Animation (int i, int x, int y, const Tile* a);
    void setDirection (state::Direction d);
    void setSpeed (float speed);
    void sync (int64_t time);
    void update (int64_t time);
  };

};

#endif
