// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H

#include "../state.hpp"
#include <SFML/Graphics.hpp>
#include <stdint.h>

namespace Render {
  class Surface;
}

#include "state/Direction.h"
#include "AnimID.h"
#include "Surface.h"

namespace Render {

  /// class Animation - 
  class Animation {
    // Associations
    Render::AnimID animID;
    // Attributes
  protected:
    state::Direction direction;
    Surface* surf;
    sf::RenderWindow* window;
    // Operations
  public:
    Animation (AnimID id, sf::RenderWindow* window);
    void setDirection (state::Direction d);
    void sync (int64_t time);
    bool update (int64_t time);
    void animate (int i, int j, int X, int Y);
    void setSurface (Surface* su);
    AnimID getAnimID ();
    state::Direction getDirection ();
  };

};

#endif
