// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <map>

namespace Render {
  class Animation;
  class Tileset;
}

#include "Animation.h"
#include "Tileset.h"

namespace Render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  private:
    <std::map<int,Animation*> animations;
  protected:
    const TileSet* tileset;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    const TileSet* getTileSet () const;
    void setTileSet (const TileSet* tileset);
    void setAnimation (int i, Animation* a);
    void printText (int x, int y, const char* msg, int spriteIdx, int w, int h);
  };

};

#endif
