// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <map>
#include "../state.hpp"
#include <vector>
#include <stdint.h>

namespace Render {
  class Surface;
  class Animation;
};
namespace state {
  class StateEvent;
  class Element;
  class Weapon;
  class State;
  class IObserver;
}

#include "state/Direction.h"
#include "state/IObserver.h"
#include "Animation.h"
#include "Surface.h"

namespace Render {

  /// class Layer - 
  class Layer : public state::IObserver {
    // Associations
    // Attributes
  protected:
    std::map<int,Animation*> animations;
    Surface* surface;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    void setSurface (Surface* surface);
    void setAnimation (int i, Animation* a);
    void printText (int x, int y, const char* msg, int spriteIdx, int w, int h);
    void stateChanged (state::StateEvent* e, std::vector<state::Element*>& list, std::vector<state::Weapon*>& weaps);
    void sync (int64_t time);
    void update (int64_t time);
    void runAnimation (int idx, int i, int j, int X, int Y, state::Direction d);
  protected:
    void update (const state::State& elementList);
  };

};

#endif
