// Generated by dia2code
#ifndef RENDER__MOBILETILE__H
#define RENDER__MOBILETILE__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class MobileTile - 
  class MobileTile : public Render::Tile {
    // Operations
  public:
    bool isMovable () const;
  };

};

#endif
