// Generated by dia2code
#ifndef RENDER__SCENELAYER__H
#define RENDER__SCENELAYER__H


namespace Render {

  enum SceneLayer {
    GRID_LAYER     = 0,
    CHARS_LAYER     = 1,
    STATE_LAYER     = 2,
    DEBUG_LAYER     = 3
  };

};

#endif
