// Generated by dia2code
#ifndef RENDER__STATICTILE__H
#define RENDER__STATICTILE__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class StaticTile - 
  class StaticTile : public Render::Tile {
    // Attributes
  protected:
    int width;
    int height;
    int X;
    int Y;
    // Operations
  public:
    bool isMovable () const;
    int getWidth () const;
    int getHeight () const;
    int getX () const;
    int getY () const;
  };

};

#endif
