// Generated by dia2code
#ifndef RENDER__STATICTILE__H
#define RENDER__STATICTILE__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class StaticTile - 
  class StaticTile : public Render::Tile {
    // Operations
  public:
    bool  isMovable () const;
  };

};

#endif
