// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace Render {

  /// class Tile - 
  class Tile {
    // Attributes
  public:
    int x;
    int y;
    int width;
    int height;
    // Operations
  public:
    Tile (int x, int y, int w, int h);
    ~Tile ();
    virtual bool isMovable () const = 0;
    int getX ();
    int getY ();
    int getWidth () const;
    int getHeight () const;
    void setX (int x);
    void setY (int y);
    void setWidth (int const w);
    void setHeight (int const h);
  };

};

#endif
