// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H


namespace Render {
  class Tile;
};
namespace state {
  class Fowl;
  class Weapon;
  class Space;
  class Field;
}

#include "Tile.h"

namespace Render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    ~TileSet ();
    const char* getImageFile () const;
    const Tile* getCharTile (char c) const;
    const Tile* getFowlTile (const state::Fowl* fo) const;
    const Tile* getWeaponTile (const state::Weapon* w);
    const Tile* getSpaceTile (const state::Space* s);
    const Tile* getFieldTile (const state::Field* fi);
  };

};

#endif
