// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace Render {

  /// class Tile - 
  class Tile {
    // Operations
  public:
    virtual ~Tile ();
    virtual bool isAnimated () const = 0;
  };

};

#endif
