// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H


namespace Render {
  class Tile;
}

#include "Tile.h"

namespace Render {

  /// class Tileset - 
  class Tileset {
    // Associations
    Render::Tile tile;
    // Operations
  public:
    const char* getImageFile () const;
    const Tile* getElementTile (const state::Element* e) const;
    const Tile* getCharTile (char c) const;
  };

};

#endif
