// Generated by dia2code
#ifndef RENDER__TYPETILEID__H
#define RENDER__TYPETILEID__H


namespace Render {

  enum TypeTileID {
    FOWL     = 0,
    PROJECTILE     = 1,
    WEAPON     = 2
  };

};

#endif
