// Generated by dia2code
#ifndef IA__AI__H
#define IA__AI__H

#include "../state.hpp"
#include "../engine.hpp"

namespace ia {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    state::State* currentState;
    // Operations
  public:
    AI (state::State* currentState);
    virtual ~AI ();
    virtual engine::Command* run (state::State* s) = 0;
  };

};

#endif
