// Generated by dia2code
#ifndef IA__DUMBIA__H
#define IA__DUMBIA__H

#include "../state.hpp"
#include "../engine.hpp"

namespace ia {
  class AI;
}

#include "AI.h"

namespace ia {

  /// class DumbIA - 
  class DumbIA : public ia::AI {
    // Attributes
  protected:
    state::State* futurState;
    // Operations
  public:
    DumbIA (state::State* currentState);
    virtual engine::Command* run (state::State* s);
  };

};

#endif
