// Generated by dia2code
#ifndef IA__DUMBIA__H
#define IA__DUMBIA__H

#include "../engine.hpp"
#include "../state.hpp"

namespace ia {

  /// class DumbIA - 
  class DumbIA {
    // Operations
  public:
    DumbIA ();
    engine::Command* runDumbIA (state::State* s, int idx);
  };

};

#endif
