// Generated by dia2code
#ifndef IA__DUMBIA__H
#define IA__DUMBIA__H

#include "../state.hpp"
#include "../engine.hpp"

namespace ia {

  /// class DumbIA - 
  class DumbIA {
    // Operations
  public:
    DumbIA ();
    void runDumbIA (state::State& s, engine::MoveFowl* mv, engine::KillFowl* k, engine::MoveCamera* v, int ite);
  };

};

#endif
