// Generated by dia2code
#ifndef IA__HEURISTICIA__H
#define IA__HEURISTICIA__H

#include "../engine.hpp"
#include "../state.hpp"

namespace ia {
  class DumbIA;
}

#include "DumbIA.h"

namespace ia {

  /// class HeuristicIA - 
  class HeuristicIA : public ia::DumbIA {
    // Operations
  public:
    engine::Command* runHeuristicIA (state::State* s, int idx);
    HeuristicIA ();
  };

};

#endif
