// Generated by dia2code
#ifndef IA__HEURISTICIA__H
#define IA__HEURISTICIA__H

#include "../state.hpp"
#include "../engine.hpp"
#include <map>

namespace ia {
  class DumbIA;
}

#include "DumbIA.h"

namespace ia {

  /// class HeuristicIA - 
  class HeuristicIA : public ia::DumbIA {
    // Operations
  public:
    HeuristicIA (state::State* currentState);
    engine::Command* run (state::State* s);
    std::map<int,int> givePonderation ();
  };

};

#endif
