// Generated by dia2code
#ifndef IA__NODETREE__H
#define IA__NODETREE__H

#include "../state.hpp"

namespace ia {
  class NodeTree;
}

#include "Reaction.h"

namespace ia {

  /// class NodeTree - 
  class NodeTree {
    // Associations
    ia::Reaction react;
    // Attributes
  public:
    NodeTree* parent;
    /// 			
    int score;
    int depth;
    state::Direction dir;
    NodeTree* son1;
    NodeTree* son2;
    NodeTree* son3;
  };

};

#endif
