// Generated by dia2code
#ifndef IA__TREE__H
#define IA__TREE__H

#include "../state.hpp"

namespace ia {
  class NodeTree;
}

#include "NodeTree.h"

namespace ia {

  /// class Tree - 
  class Tree {
    // Associations
    // Attributes
  protected:
    NodeTree* root;
    state::State* currentState;
    // Operations
  public:
    Tree (state::State* s);
    ~Tree ();
  };

};

#endif
