// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    NONE     = 0,
    NORD     = 1,
    OUEST     = 2,
    SUD     = 3,
    EST     = 4
  };

};

#endif
