// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <string>
#include <map>
#include <memory>

namespace state {
  class Element;
  class IElement;
}

#include "Element.h"
#include "IElement.h"

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Associations
    // Attributes
  private:
    std::map<std::string, std::unique_ptr<IElement>> staticList;
    std::map<std::string, std::unique_ptr<IElement>> mobileList;
    // Operations
  public:
    ElementFactory ();
    Element* create (std::string clef, bool movable);
    void enregistrer (std::string clef, IElement* creator, bool movable);
  };

};

#endif
