// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <stdlib.h>

namespace state {
  class Element;
}

#include "Direction.h"
#include "TypeID.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeID type;
    // Attributes
  protected:
    size_t X;
    size_t Y;
    Direction direction;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual TypeID getTypeID () const = 0;
    int getX () const;
    int getY () const;
    Direction getOrientation () const;
    void setX (int x);
    void setY (int y);
    void setOrientation (Direction direction);
    virtual bool isStatic () const = 0;
    virtual Element* clone () const = 0;
    virtual bool equals (const Element& other) const;
  };

};

#endif
