// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "Direction.h"
#include "TypeID.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeID type;
    // Attributes
  protected:
    size-t X;
    size-t Y;
    Direction direction;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual TypeID const getTypeID () = 0;
    int const getX ();
    int const getY ();
    Direction const getOrientation ();
    void setX (int x);
    void setY (int y);
    void setOrientation (Direction direction);
    virtual bool const isStatic () = 0;
    virtual Element* const clone () = 0;
    virtual bool const equals (const Element& other);
  };

};

#endif
