// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <string>
#include <map>
#include <memory>

namespace state {
  class Element;
  class IElement;
}

#include "TypeID.h"
#include "Element.h"
#include "IElement.h"

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Associations
    // Attributes
  private:
    std::map<std::string, std::unique_ptr<IElement>> list;
    // Operations
  public:
    Element* create (std::string& clef, TypeID id);
    void enregistrer (std::string& clef, IElement* creator);
  };

};

#endif
