// Generated by dia2code
#ifndef STATE__FIELDTYPEID__H
#define STATE__FIELDTYPEID__H


namespace state {

  enum FieldTypeID {
    BIGBROWN1     = 1,
    BIGBROWN2     = 2,
    BIGBROWN3     = 3,
    BIGBROWN4     = 4,
    BIGBROWN5     = 5,
    BIGBROWN6     = 6,
    BIGSTONE1     = 7,
    BIGSTONE2     = 8,
    BIGSTONE3     = 9,
    BIGSTONE4     = 10,
    BIGSTONE5     = 11,
    BIGSTONE6     = 12,
    CIRCLEBROWN1     = 13,
    CIRCLEBROWN2     = 14,
    CIRCLEBROWN3     = 15,
    CIRCLEBROWN4     = 16,
    CIRCLESTONE1     = 17,
    CIRCLESTONE2     = 18,
    CIRCLESTONE3     = 19,
    CIRCLESTONE4     = 20
  };

};

#endif
