// Generated by dia2code
#ifndef STATE__FIELDCREATOR__H
#define STATE__FIELDCREATOR__H

#include <string>

namespace state {
  class Element;
  class IElement;
  class Field;
}

#include "IElement.h"
#include "Field.h"

namespace state {

  /// class FieldCreator - 
  class FieldCreator : public state::IElement {
    // Operations
  public:
    Element* create (std::string st);
  };

};

#endif
