// Generated by dia2code
#ifndef STATE__FIELDTYPEID__H
#define STATE__FIELDTYPEID__H


namespace state {

  enum FieldTypeID {
    NEANT     = 0,
    BIGBROWN1     = 1,
    BIGBROWN2     = 2,
    BIGBROWN3     = 3,
    BIGBROWN4     = 4,
    BIGBROWN5     = 5,
    BIGBROWN6     = 6,
    BIGSTONE1     = 7,
    BIGSTONE2     = 8,
    BIGSTONE3     = 9,
    BIGSTONE4     = 10,
    BIGSTONE5     = 11,
    BIGSTONE6     = 12,
    CIRCLEBROWN1     = 13,
    CIRCLEBROWN2     = 14,
    CIRCLEBROWN3     = 15,
    CIRCLEBROWN4     = 16,
    CIRCLESTONE1     = 17,
    CIRCLESTONE2     = 18,
    CIRCLESTONE3     = 19,
    CIRCLESTONE4     = 20,
    SMALLBROWN1     = 21,
    SMALLBROWN2     = 22,
    SMALLBROWN3     = 23,
    SMALLBROWN4     = 24,
    SMALLBROWN5     = 25,
    SMALLBROWN6     = 26,
    SMALLBROWN7     = 27,
    SMALLBROWN8     = 28,
    SMALLSTONE1     = 29,
    SMALLSTONE2     = 30,
    SMALLSTONE3     = 31,
    SMALLSTONE4     = 32,
    SMALLSTONE5     = 33,
    SMALLSTONE6     = 34,
    SMALLSTONE7     = 35,
    SMALLSTONE8     = 36
  };

};

#endif
