// Generated by dia2code
#ifndef STATE__FIELD__H
#define STATE__FIELD__H


namespace state {
  class StaticElement;
}

#include "TypeID.h"
#include "FieldTypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Field - 
  class Field : public state::StaticElement {
    // Associations
    state::FieldTypeID status;
    // Attributes
  protected:
    TypeID type;
    // Operations
  public:
    Field (FieldTypeID id);
    bool isSpace () const;
    TypeID getTypeID () const;
    FieldTypeID getFieldTypeID ();
    void setFieldTypeID (FieldTypeID id);
    ~Field ();
  };

};

#endif
