// Generated by dia2code
#ifndef STATE__FIELDCREATOR__H
#define STATE__FIELDCREATOR__H


namespace state {
  class Element;
  class IElement;
  class Field;
}

#include "FieldTypeID.h"
#include "IElement.h"
#include "Field.h"

namespace state {

  /// class FieldCreator - 
  class FieldCreator : public state::IElement {
    // Attributes
  private:
    FieldTypeID id;
    // Operations
  public:
    Element* create ();
    FieldCreator (FieldTypeID id);
  };

};

#endif
