// Generated by dia2code
#ifndef STATE__FIELD__H
#define STATE__FIELD__H


namespace state {
  class Element;
  class StaticElement;
}

#include "FieldTypeID.h"
#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Field - 
  class Field : public state::StaticElement {
    // Associations
    state::FieldTypeID status;
    // Operations
  public:
    Field (FieldTypeID id);
    bool isSpace () const;
    TypeID getTypeID () const;
    FieldTypeID getFieldTypeID () const;
    void setFieldTypeID (FieldTypeID id);
    Element* clone () const;
    bool equals (const Element& other) const;
  };

};

#endif
