// Generated by dia2code
#ifndef STATE__FOWLCREATOR__H
#define STATE__FOWLCREATOR__H


namespace state {
  class Element;
  class IElement;
  class Fowl;
}

#include "FowlStatus.h"
#include "FowlColor.h"
#include "IElement.h"
#include "Fowl.h"

namespace state {

  /// class FowlCreator - 
  class FowlCreator : public state::IElement {
    // Attributes
  private:
    FowlStatus status;
    FowlColor color;
    // Operations
  public:
    Element* create ();
    FowlCreator (FowlColor color, FowlStatus status);
  };

};

#endif
