// Generated by dia2code
#ifndef STATE__FOWLCOLOR__H
#define STATE__FOWLCOLOR__H


namespace state {

  enum FowlColor {
    BLANC     = 1,
    VERT     = 2,
    NOIR     = 3,
    BEIGE     = 4,
    KAKI     = 5,
    MARRON     = 6,
    GRIS     = 7,
    ORANGE     = 8
  };

};

#endif
