// Generated by dia2code
#ifndef STATE__FOWLCOLOR__H
#define STATE__FOWLCOLOR__H


namespace state {

  enum FowlColor {
    BLANK     = 0,
    WHITE     = 1,
    GREEN     = 2,
    BLACK     = 3,
    BEIGE     = 4,
    KHAKI     = 5,
    BROWN     = 6,
    GREY     = 7,
    ORANGE     = 8
  };

};

#endif
