// Generated by dia2code
#ifndef STATE__FOWLSTATUS__H
#define STATE__FOWLSTATUS__H


namespace state {

  enum FowlStatus {
    ALIVE     = 1,
    DEAD     = 2,
    TOUCHED     = 3,
    WAITING     = 4
  };

};

#endif
