// Generated by dia2code
#ifndef STATE__FOWLWEAPON__H
#define STATE__FOWLWEAPON__H


namespace state {

  enum FowlWeapon {
    CHAINSAW     = 0,
    LIGHTSABER     = 1,
    AXE     = 2,
    SWORD     = 3,
    NINJASABER     = 4,
    SOCKET     = 5,
    MAGICWAND     = 6
  };

};

#endif
