// Generated by dia2code
#ifndef STATE__FOWLSTATUS__H
#define STATE__FOWLSTATUS__H


namespace state {

  enum FowlStatus {
    ALIVE_FACE     = 1,
    ALIVE_LEFT     = 2,
    ALIVE_RIGHT     = 3,
    DEAD     = 4,
    TOUCHED     = 5,
    WAITING     = 6,
    HITTING     = 7
  };

};

#endif
