// Generated by dia2code
#ifndef STATE__FOWL__H
#define STATE__FOWL__H

#include <vector>

namespace state {
  class Weapon;
  class Element;
  class MobileElement;
}

#include "Weapon.h"
#include "FowlStatus.h"
#include "Direction.h"
#include "MobileElement.h"

namespace state {

  /// class Fowl - 
  class Fowl : public state::MobileElement {
    // Associations
    state::FowlStatus status;
    // Attributes
  protected:
    /// 		
    int HP;
    int color;
    String name;
    std::vector<Weapon> weapons;
    // Operations
  public:
    Fowl ();
    bool const isFowl ();
    TypeID const getTypeID ();
    int getColor ();
    String getName ();
    int getHP ();
    void setColor (int c);
    void setName (String name);
    void setHP (int hp);
    FowlStatus const getFowlStatus ();
    void setFowlStatus (FowlStatus status);
    void getBox ();
    Direction getDirection ();
    void setDirection (Direction dir);
    void addWeapon (Weapon weapon, std::vector<Weapon> weapons);
    Element* const clone ();
    bool const equals (const Element& other);
  };

};

#endif
