// Generated by dia2code
#ifndef STATE__IELEMENT__H
#define STATE__IELEMENT__H

#include <string>

namespace state {
  class Element;
}

namespace state {

  // interface
  /// class IElement - 
  class IElement {
    // Operations
  public:
    virtual Element* create (std::string st) = 0;
  };

};

#endif
