// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H

#include <vector>
#include "../state.hpp"

namespace state {
  class StateEvent;
  class Element;
  class Weapon;
}

namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void stateChanged (StateEvent* e, std::vector<Element*>& list, std::vector<state::Weapon*>& weaps) = 0;
  };

};

#endif
