// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H

#include <vector>

namespace state {
  class StateEvent;
  class Element;
}

namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void stateChanged (StateEvent* e) = 0;
    virtual void stateChanged (StateEvent* e, std::vector<Element*> list) = 0;
  };

};

#endif
