// Generated by dia2code
#ifndef STATE__IOBSERVER__H
#define STATE__IOBSERVER__H


namespace state {
  class StateEvent;
}

namespace state {

  // interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void stateChanged (const StateEvent& e) = 0;
  };

};

#endif
