// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H

#include <stdlib.h>

namespace state {
  class Element;
}

#include "Direction.h"
#include "Orientation.h"
#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Associations
    state::Orientation orient;
    state::Direction direction;
    // Attributes
  protected:
    /// 												
    size_t speed;
    size_t position;
    // Operations
  public:
    MobileElement ();
    virtual bool isStatic () const;
    Direction getDirection () const;
    void setDirection (Direction dir);
    Orientation getOrientation () const;
    void setOrientation (Orientation ori);
    void setSpeed (size_t s);
    void setPosition (size_t p);
    virtual bool isFowl () const = 0;
  };

};

#endif
