// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H

#include <stdlib.h>

namespace state {
  class Element;
}

#include "Direction.h"
#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Associations
    state::Direction direction;
    // Attributes
  protected:
    /// 												
    size_t speed;
    size_t position;
    // Operations
  public:
    MobileElement ();
    bool isStatic () const;
    virtual bool isFowl () const = 0;
    virtual Direction getDirection () const = 0;
    virtual void setDirection (Direction dir) = 0;
    void setSpeed (size_t s);
    void setPosition (size_t p);
    virtual bool equals (const Element& other) const;
  };

};

#endif
