// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H

#include <stdlib.h>

namespace state {
  class Element;
}

#include "Direction.h"
#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Associations
    state::Direction direction;
    // Attributes
  protected:
    /// 												
    size_t speed;
    size_t position;
    // Operations
  public:
    MobileElement ();
    bool const isStatic ();
    virtual bool const isFowl () = 0;
    virtual Direction const getDirection () = 0;
    virtual void setDirection (Direction dir) = 0;
    virtual void setSpeed (size_t s) = 0;
    void setPosition (size_t p);
    virtual bool const equals (const Element& other);
  };

};

#endif
