// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class IObserver;
  class StateEvent;
  class Element;
}

#include "IObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    std::vector<IObserver*> observers;
    // Operations
  public:
    virtual ~Observable ();
    void registerObserver (IObserver* o);
    void notifyObservers (StateEvent* e);
    void notifyObservers (StateEvent* e, std::vector<Element*> list);
  };

};

#endif
