// Generated by dia2code
#ifndef STATE__ORIENTATION__H
#define STATE__ORIENTATION__H


namespace state {

  enum Orientation {
    OriNONE     = 1,
    OriEST     = 0,
    OriEST30     = 30,
    OriNORDEST     = 45,
    OriEST60     = 60,
    OriNORD     = 90,
    OriNORD30     = 120,
    OriNORDOUEST     = 135,
    OriNORD60     = 150,
    OriOUEST     = 180,
    OriOUEST30     = 210,
    OriSUDOUEST     = 225,
    OriOUEST60     = 240,
    OriSUD     = 270,
    OriSUD30     = 300,
    OriSUDEST     = 315,
    OriSUD60     = 330
  };

};

#endif
