// Generated by dia2code
#ifndef STATE__SPACECREATOR__H
#define STATE__SPACECREATOR__H


namespace state {
  class Element;
  class IElement;
  class Space;
}

#include "SpaceTypeID.h"
#include "IElement.h"
#include "Space.h"

namespace state {

  /// class SpaceCreator - 
  class SpaceCreator : public state::IElement {
    // Attributes
  private:
    SpaceTypeID id;
    // Operations
  public:
    Element* create ();
    SpaceCreator (SpaceTypeID id);
  };

};

#endif
