// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeID {
    EMPTY     = 1,
    START     = 2,
    BOX     = 3,
    WATER1     = 4,
    WATER2     = 5,
    EXTRA     = 6
  };

};

#endif
