// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class StaticElement;
}

#include "SpaceTypeID.h"
#include "TypeID.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Associations
    state::SpaceTypeID status;
    // Operations
  public:
    Space (SpaceTypeID id);
    bool isSpace () const;
    TypeID getTypeID () const;
    SpaceTypeID getSpaceTypeID ();
    void setSpaceTypeID (SpaceTypeID id);
  };

};

#endif
