// Generated by dia2code
#ifndef STATE__SPACECREATOR__H
#define STATE__SPACECREATOR__H


namespace state {
  class Element;
  class IElement;
  class Space;
}

#include "IElement.h"
#include "Space.h"

namespace state {

  /// class SpaceCreator - 
  class SpaceCreator : public state::IElement {
    // Operations
  public:
    Element* create ();
  };

};

#endif
