// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class MobileElement;
  class ElementFactory;
  class StaticElement;
  class Observable;
}

#include "Observable.h"
#include "StaticElement.h"
#include "ElementFactory.h"
#include "MobileElement.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  protected:
    std::vector<MobileElement*> elements;
    ElementFactory* factory;
    std::vector<StaticElement*> background;
    // Operations
  public:
    State ();
    ~State ();
    void setElementFactory (ElementFactory* f);
    std::vector<MobileElement*> getMobileElements ();
    MobileElement* getMobileElement (int idx);
    std::vector<StaticElement*> getStaticElements ();
    StaticElement* getStaticElement (int idx);
    void loadLevel (const char* file_name);
  };

};

#endif
