// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventID {
    HP_LOST     = 0,
    FOWL_DEAD     = 1,
    WEAPON_OUT     = 2,
    WEAPON_IN     = 3,
    FILEMAP_LOADED     = 4,
    FILECHAR_LOADED     = 5,
    FOWL_MOVE_RIGHT     = 6,
    FOWL_MOVE_LEFT     = 7,
    FOWL_STOP     = 8,
    FOWL_SELECTED     = 9,
    FOWL_FALL     = 10,
    FOWL_JUMP_RIGHT     = 11,
    FOWL_JUMP_LEFT     = 12,
    FOWL_HITTING     = 13
  };

};

#endif
