// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventID {
    HP_LOST     = 0,
    FOWL_DEAD     = 1,
    WEAPON_OUT     = 2,
    WEAPON_IN     = 3,
    FILEMAP_LOADED     = 4,
    FILECHAR_LOADED     = 5
  };

};

#endif
