// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class IObserver;
}

#include "StateEventID.h"
#include "IObserver.h"

namespace state {

  /// class StateEvent - 
  class StateEvent {
    // Associations
    state::StateEventID stateevent;
    // Operations
  public:
    StateEvent (StateEventID id);
    virtual ~StateEvent ();
    StateEventID getStateEventID () const;
  };

};

#endif
