// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeID {
    FIELD     = 1,
    SPACE     = 2,
    FOWL     = 3,
    WEAPON     = 4
  };

};

#endif
