// Generated by dia2code
#ifndef STATE__WEAPONSTATUS__H
#define STATE__WEAPONSTATUS__H


namespace state {

  enum WeaponStatus {
    GUN     = 1,
    MELEE     = 2,
    THROWABLE     = 3,
    BOMB     = 4,
    AMMO     = 5
  };

};

#endif
