// Generated by dia2code
#ifndef STATE__WEAPON__H
#define STATE__WEAPON__H


namespace state {
  class MobileElement;
}

#include "TypeID.h"
#include "WeaponStatus.h"
#include "MobileElement.h"

namespace state {

  /// class Weapon - 
  class Weapon : public state::MobileElement {
    // Associations
    state::WeaponStatus status;
    // Attributes
  protected:
    int power;
    int weight;
    int ammo;
    // Operations
  public:
    Weapon ();
    bool isFowl () const;
    TypeID getTypeID () const;
    int getPower () const;
    int getWeight () const;
    void setPower (int power);
    void setWeight (int weight);
    WeaponStatus getWeaponStatus () const;
    void setWeaponStatus (WeaponStatus status);
  };

};

#endif
