// Generated by dia2code
#ifndef WEBSERVICES__SERVICESMANAGER__H
#define WEBSERVICES__SERVICESMANAGER__H

#include <vector>
#include <memory>
#include <string>

namespace webservices {
  class AbstractService;
}

#include "AbstractService.h"
#include "HttpStatus.h"

namespace webservices {

  /// class ServicesManager - 
  class ServicesManager {
    // Associations
    // Attributes
  protected:
    std::vector<std::unique_ptr<AbstractService> > services;
    // Operations
  public:
    void registerService (std::unique_ptr<AbstractService> service);
    AbstractService* findService (const std::string& url) const;
    HttpStatus queryService (std::string& out, const std::string& in, const std::string& url, const std::string& method);
  };

};

#endif
