// Generated by dia2code
#ifndef WEBSERVICES__USERSERVICE__H
#define WEBSERVICES__USERSERVICE__H


namespace webservices {
  class UserDB;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "UserDB.h"

namespace webservices {

  /// class UserService - 
  class UserService : public webservices::AbstractService {
    // Associations
    // Attributes
  protected:
    UserDB& userDB;
    // Operations
  public:
    UserService (UserDB& userDB);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus post (const Json::Value& in, int id);
    HttpStatus put (Json::Value& out, const Json::Value& in);
    HttpStatus remove (int id);
  };

};

#endif
