// Generated by dia2code
#ifndef WEBSERVICES__USER__H
#define WEBSERVICES__USER__H

#include <string>

namespace webservices {

  /// class User - 
  class User {
    // Attributes
  public:
    std::string name;
    int age;
    // Operations
  public:
    User (std::string name, int age);
  };

};

#endif
