// Generated by dia2code
#ifndef WEBSERVICES__USER__H
#define WEBSERVICES__USER__H


namespace webservices {

  /// class User - 
  class User {
    // Attributes
  public:
    string name;
    int age;
    // Operations
  public:
    User (string name, int age);
  };

};

#endif
