// Generated by dia2code
#ifndef WEBSERVICES__USERDB__H
#define WEBSERVICES__USERDB__H

#include <map>
#include <memory>

namespace webservices {
  class User;
}

#include "User.h"

namespace webservices {

  /// class UserDB - 
  class UserDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    std::map<int,std::unique_ptr<User> > users;
    // Operations
  public:
    UserDB ();
    const User* getUser (int id) const;
    int addUser (std::unique_ptr<User> user);
    void setUser (int id, std::unique_ptr<User> user);
    void removeUser (int id);
  };

};

#endif
