// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "Render/Tile.h"
#include "Render/StaticTile.h"
#include "Render/TypeTileID.h"
#include "Render/MobileTile.h"
#include "Render/Tileset.h"
#include "Render/Animation.h"
#include "Render/Layer.h"
#endif
