// Generated by dia2code
#ifndef __WEBSERVICES__H
#define __WEBSERVICES__H

#include "webservices/HttpStatus.h"
#include "webservices/AbstractService.h"
#include "webservices/User.h"
#include "webservices/UserDB.h"
#include "webservices/UserService.h"
#include "webservices/VersionService.h"
#include "webservices/ServiceException.h"
#include "webservices/ServicesManager.h"
#endif
